// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGBAzPeRC2hHMrRJapAG-x2qJxtPt_7lA',
    appId: '1:1038243894712:web:bbc67a4182ea5139b62b4d',
    messagingSenderId: '1038243894712',
    projectId: 'ziyonstar',
    authDomain: 'ziyonstar.firebaseapp.com',
    storageBucket: 'ziyonstar.firebasestorage.app',
    measurementId: 'G-JSKBCM8CSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE0n5VCQwPwoagZEos6zXRW-_C9FNaLXE',
    appId: '1:1038243894712:android:06932edf5929bba4b62b4d',
    messagingSenderId: '1038243894712',
    projectId: 'ziyonstar',
    storageBucket: 'ziyonstar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu78q3BEFDrMS1DyAjUlMe1jZ8v87fHUI',
    appId: '1:1038243894712:ios:34939be633612ee3b62b4d',
    messagingSenderId: '1038243894712',
    projectId: 'ziyonstar',
    storageBucket: 'ziyonstar.firebasestorage.app',
    iosBundleId: 'com.patelpulseventures.ziyonstar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu78q3BEFDrMS1DyAjUlMe1jZ8v87fHUI',
    appId: '1:1038243894712:ios:34939be633612ee3b62b4d',
    messagingSenderId: '1038243894712',
    projectId: 'ziyonstar',
    storageBucket: 'ziyonstar.firebasestorage.app',
    iosBundleId: 'com.patelpulseventures.ziyonstar',
  );
}
